//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace VanToDo
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ToDoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ToDoEntities object using the connection string found in the 'ToDoEntities' section of the application configuration file.
        /// </summary>
        public ToDoEntities() : base("name=ToDoEntities", "ToDoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ToDoEntities object.
        /// </summary>
        public ToDoEntities(string connectionString) : base(connectionString, "ToDoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ToDoEntities object.
        /// </summary>
        public ToDoEntities(EntityConnection connection) : base(connection, "ToDoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ToDoItem> ToDoItems
        {
            get
            {
                if ((_ToDoItems == null))
                {
                    _ToDoItems = base.CreateObjectSet<ToDoItem>("ToDoItems");
                }
                return _ToDoItems;
            }
        }
        private ObjectSet<ToDoItem> _ToDoItems;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ToDoItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToToDoItems(ToDoItem toDoItem)
        {
            base.AddObject("ToDoItems", toDoItem);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VanToDo", Name="ToDoItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ToDoItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ToDoItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="index">Initial value of the Index property.</param>
        /// <param name="done">Initial value of the Done property.</param>
        public static ToDoItem CreateToDoItem(global::System.Guid id, global::System.Int64 index, global::System.Boolean done)
        {
            ToDoItem toDoItem = new ToDoItem();
            toDoItem.Id = id;
            toDoItem.Index = index;
            toDoItem.Done = done;
            return toDoItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Index
        {
            get
            {
                return _Index;
            }
            set
            {
                OnIndexChanging(value);
                ReportPropertyChanging("Index");
                _Index = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Index");
                OnIndexChanged();
            }
        }
        private global::System.Int64 _Index;
        partial void OnIndexChanging(global::System.Int64 value);
        partial void OnIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DueDateTime
        {
            get
            {
                return _DueDateTime;
            }
            set
            {
                OnDueDateTimeChanging(value);
                ReportPropertyChanging("DueDateTime");
                _DueDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DueDateTime");
                OnDueDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _DueDateTime;
        partial void OnDueDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnDueDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Done
        {
            get
            {
                return _Done;
            }
            set
            {
                OnDoneChanging(value);
                ReportPropertyChanging("Done");
                _Done = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Done");
                OnDoneChanged();
            }
        }
        private global::System.Boolean _Done;
        partial void OnDoneChanging(global::System.Boolean value);
        partial void OnDoneChanged();

        #endregion
    
    }

    #endregion
    
}
